version: '3.2'

services:
  dev:
    build:
      context:  ./
      dockerfile: Dockerfile.dev
      cache_from:
        - zooniverse/hermes:dev
    volumes:
      - ${HOME}/.hermes/:/root/.hermes/
      - ${HOME}/.aws/:/root/.aws/
      - ${HOME}/.ssh/:/root/.ssh/
      - ${HOME}/.docker/:/root/.docker/
      - ${HOME}/.dockercfg:/root/.dockercfg
      - ${HOME}:${HOME}
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    working_dir: ${PWD}

  stable:
    build:
      context: ./
      dockerfile: Dockerfile.stable
      cache_from:
        - zooniverse/hermes:stable
    volumes:
      - ${HOME}/.hermes/:/root/.hermes/
      - ${HOME}/.aws/:/root/.aws/
      - ${HOME}:${HOME}
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
    working_dir: ${PWD}

  dev2:
    build:
      context:  ./
      dockerfile: Dockerfile.dev2
      cache_from:
        - zooniverse/hermes:dev-python2
    volumes:
      - ${HOME}/.hermes/:/root/.hermes/
      - ${HOME}/.aws/:/root/.aws/
      - ${HOME}:${HOME}
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
    working_dir: ${PWD}

  stable2:
    build:
      context: ./
      dockerfile: Dockerfile.stable2
      cache_from:
        - zooniverse/hermes:stable-python2
    volumes:
      - ${HOME}/.hermes/:/root/.hermes/
      - ${HOME}/.aws/:/root/.aws/
      - ${HOME}:${HOME}
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
    working_dir: ${PWD}
