FROM python:2.7

WORKDIR /usr/src/hermes

RUN curl https://get.docker.com | bash -
RUN pip install docker-compose

COPY setup.py .

RUN pip install .

COPY . .

RUN pip install -U .

ENTRYPOINT [ "hermes" ]
